name: Deploy to Heroku

on:
  push:
    branches:
      - master  # Trigger this action on the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Set environment variable for OpenSSL
      run: export NODE_OPTIONS=--openssl-legacy-provider

    - name: Install dependencies
      run: npm install

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Login to Heroku using API key
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Heroku API Key from Secrets
      run: heroku auth:token

    - name: Set Heroku git remote
      run: heroku git:remote -a stanley-memories

    - name: Configure Git user
      run: |
        git config --global user.email "xstanz@gmail.com"
        git config --global user.name "Stanley Luong"
    
    - name: Commit changes if any
      run: |
        git add .
        git commit -m "Automated deploy" || echo "No changes to commit"

    - name: Deploy to Heroku
      run: git push heroku master --force  # Force push to overwrite Heroku code
